services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx
    ports:
      -  "443:443"
    volumes:
      - /home/${USER}/data/www:/var/www/html
    secrets:
      - selfsigned.key
      - selfsigned.crt
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - /home/${USER}/data/db_data:/var/lib/mysql
    ports:
      - "3306"
    networks:
      - inception
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    expose:
      - 9000
    volumes:
      - /home/${USER}/data/www:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

networks:
  inception:
    driver: bridge

secrets:
  selfsigned.key:
    file: ../secrets/selfsigned.key
  selfsigned.crt:
    file: ../secrets/selfsigned.crt