services:
  nginx:
    image: nginx
    ports:
      -  "8080:80"
    volumes:
      - ./www:/var/www/html
  mariadb:
    build:
      context: ./requirements/mariadb
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
#  wordpress:
 #   image: wordpress
    #ports:
     # - 8080:80
  #  volumes:
   #   - ./www:/var/www/html
