services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports:
      -  "8080:443"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306"
    networks:
      - inception
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    expose:
      - 9000
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception

networks:
  inception:
    driver: bridge